version: "3.9"

services:
  waha:
    image: devlikeapro/waha
    container_name: waha_service
    restart: always
    expose:
      - "3000"
    environment:
      - WAHA_DOMAIN=waha.rehubpro.kz
      - VIRTUAL_HOST=waha.rehubpro.kz
      - LETSENCRYPT_HOST=waha.rehubpro.kz
      - LETSENCRYPT_EMAIL=admin@rehubpro.kz
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WAHA_PRINT_QR=true
    volumes:
      - ./waha_sessions:/app/.sessions
    networks:
      - core_backend
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  whatsapp-gateway:
    build: ./gateway
    container_name: whatsapp_gateway
    restart: always
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=wh-gateway.rehubpro.kz
      - LETSENCRYPT_HOST=wh-gateway.rehubpro.kz
      - LETSENCRYPT_EMAIL=admin@rehubpro.kz
      - TZ=Asia/Almaty
    volumes:
      - ./gateway/data:/app/data
    networks:
      - core_backend
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  core_backend:
    external: true